---

- name: install telegraf related packages
  yum: name={{ item }} state=present
  with_items:
    - telegraf

- name: template /etc/telegraf/telegraf.conf
  template: src=etc/telegraf/telegraf.conf.j2
            dest=/etc/telegraf/telegraf.conf
            mode=644 backup=yes
  notify: restart telegraf

- name: start and enable telegraf
  service: name={{ item }} state=started enabled=yes
  with_items:
    - telegraf
