---

- name: copy influxdb yum repo file
  copy: src=influxdata.repo dest=/etc/yum.repos.d/influxdata.repo

- name: install telegraf related packages
  yum: name={{ item }} state=present
  with_items:
    - telegraf

- name: include https.yml
  include: https.yml
  when: telegraf_influxdb_use_https is defined and telegraf_influxdb_use_https == "true"

- name: template /usr/lib/systemd/system/telegraf.service
  template: src=usr/lib/systemd/system/telegraf.service.j2
            dest=/usr/lib/systemd/system/telegraf.service
            mode=644 backup=yes
  notify: restart telegraf

- name: template /etc/telegraf/telegraf.conf
  template: src=etc/telegraf/telegraf.conf.j2
            dest=/etc/telegraf/telegraf.conf
            mode=644 backup=yes
  notify: restart telegraf

- name: template /etc/telegraf/telegraf.d/sysstat.conf
  template: src=etc/telegraf/telegraf.d/sysstat.conf.j2
            dest=/etc/telegraf/telegraf.d/sysstat.conf
            mode=644 backup=yes
  notify: restart telegraf

- name: start and enable telegraf
  service: name={{ item }} state=started enabled=yes
  with_items:
    - telegraf

- name: check if telegraf is running
  shell: systemctl status telegraf | grep running

